version: '3.8'
services:
  postgres:
    image: postgres
    env_file:
      - ./env/postgres.env
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql/data
  dotnet:
    image: zunaa21/nosh-nexus-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  angular:
    image: zunaa21/nosh-nexus-owner-client
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dotnet